### ISSUE TITLE
produce tag v0.0.9

### ISSUE THREAD

**Issue by inmarelibero** [kusflo/PrestaShopWebService#2]
Hi, could you produce tag `v0.0.9`? I saw that the last tag is not aligned with `master` branch

in particular, I saw that https://github.com/kusflo/PrestaShopWebService/blob/master/src/Entities/PShopWs.php#L31 is a fundamental improvement, not included in tag `v0.0.8`

**Comment by kusflo** [comment]
Hi, the tag v0.0.9 is created. If it seems good to you, I close the issue.

**Comment by inmarelibero** [comment]
fantastic

good for me, thank you
